### ISSUE TITLE
Icon for .h files should not be 'Apple'

### ISSUE THREAD

**Issue by bsnsk** [wyze/atom-seti-icons#26]
I use .h files as C/C++ project headers, but the icons are 'Apple's (recognized as Objective C files). 

Perhaps this should obey the C/C++ style? Otherwise it is really weird to have these 'Apple's in my project directory icons.

**Comment by wyze** [comment]
Since this package just mirrors the icons from Seti UI, you would need to create the issue over there. But it looks like someone has done that already: https://github.com/jesseweed/seti-ui/issues/294 .. I would add a comment in that issue, and if the icon gets changed, then it will migrate over this way.
